title: "Proyecto Prius: Estación de Carga Solar"
description: "Implementación de una estación de carga solar para un Toyota Prius convertido en híbrido enchufable. Utilizando paneles solares y baterías de respaldo, suministramos energía limpia y renovable para la carga del vehículo."
keywords:
  - "Toyota Prius"
  - "híbrido enchufable"
  - "carga solar"
  - "paneles solares"
  - "energía renovable"
  - "baterías de respaldo"
  - "vehículos eléctricos"
  - "proyectos de energía"
  - "sistema de carga solar"
  - "conversión de vehículos"
  - "tecnología limpia"

author: Lorenzo Valles
url: "https://github.com/Lorevalles/Cargador_Solar"
baseurl: "/"
github_username: "Lorevalles"
theme: jekyll-theme-minimal

# SEO and Social Sharing
seo:
  type: "website"
  title: "Proyecto Prius: Estación de Carga Solar"
  description: "Implementación de una estación de carga solar para un Toyota Prius convertido en híbrido enchufable, utilizando energía limpia y renovable."
  image: "/assets/images/Estacion_Carga_Solar.jpg"
  twitter:
    card: "summary_large_image"
    site: "@LorenzoValles"
    creator: "@LorenzoValles"
  og:
    type: "website"
    title: "Proyecto Prius: Estación de Carga Solar"
    description: "Implementación de una estación de carga solar para un Toyota Prius convertido en híbrido enchufable, utilizando energía limpia y renovable."
    image: "/assets/images/Estacion_Carga_Solar.jpg"
    url: "https://github.com/Lorevalles/Cargador_Solar"
